import "@styles/globals.css";
import LocaleProvider from "../../context/locale/Provider";
import { i18n } from "../../i18n.config";

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // console.log(locale);
  return (
    <html lang={locale}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <main>
          <LocaleProvider locale={locale}>{children}</LocaleProvider>
        </main>
      </body>
    </html>
  );
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ locale }));
}
